// Code generated by gen-styles from kukuvaia-theme.yaml. DO NOT EDIT.

package tui

import "github.com/charmbracelet/lipgloss"

// --- Color constants ---

var (
	ColorPrimary    = lipgloss.Color("#00FF41")
	ColorSuccess    = lipgloss.Color("#00FF41")
	ColorError      = lipgloss.Color("#FF4444")
	ColorWarning    = lipgloss.Color("#FFB800")
	ColorMuted      = lipgloss.Color("#008F11")
	ColorText       = lipgloss.Color("#00FF41")
	ColorBackground = lipgloss.Color("#000000")
	ColorSurface    = lipgloss.Color("#0A0A0A")
	ColorBorder     = lipgloss.Color("#008F11")
)

// --- Status colors ---

var (
	ColorPass    = lipgloss.Color("#00FF41")
	ColorFail    = lipgloss.Color("#FF4444")
	ColorPending = lipgloss.Color("#FFB800")
	ColorSkip    = lipgloss.Color("#008F11")
)

// --- Progress colors ---

var (
	ColorProgressFilled = lipgloss.Color("#00FF41")
	ColorProgressEmpty  = lipgloss.Color("#008F11")
	ColorSpinner        = lipgloss.Color("#00FF41")
)

// --- Code block colors ---

var (
	ColorCodeBg     = lipgloss.Color("#0A0A0A")
	ColorCodeBorder = lipgloss.Color("#008F11")
	ColorCodeText   = lipgloss.Color("#00FF41")
)

// --- Table colors ---

var (
	ColorTableHeaderBg = lipgloss.Color("#008F11")
	ColorTableHeaderFg = lipgloss.Color("#00FF41")
	ColorTableRowAlt   = lipgloss.Color("#0A0A0A")
	ColorTableBorder   = lipgloss.Color("#008F11")
)

// --- Spacing ---

const (
	SpacingBlockGap   = 1
	SpacingSectionGap = 2
)

// --- Composed styles ---

var (
	TitleStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(ColorPrimary)

	ErrorStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(ColorError)

	WarningStyle = lipgloss.NewStyle().
			Foreground(ColorWarning)

	MutedStyle = lipgloss.NewStyle().
			Foreground(ColorMuted)

	PanelStyle = lipgloss.NewStyle().
			Border(lipgloss.RoundedBorder()).
			BorderForeground(ColorBorder).
			Padding(0, 1)

	PanelTitleStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("#00FF41")).
			Background(ColorBorder).
			Padding(0, 1)

	CodeBlockStyle = lipgloss.NewStyle().
			Background(ColorCodeBg).
			Border(lipgloss.RoundedBorder()).
			BorderForeground(ColorCodeBorder).
			Padding(0, 1)

	TableHeaderStyle = lipgloss.NewStyle().
				Bold(true).
				Foreground(ColorTableHeaderFg).
				Background(ColorTableHeaderBg).
				Padding(0, 1)

	UserMessageStyle = lipgloss.NewStyle().
				Foreground(ColorPrimary).
				Bold(true)

	SpinnerStyle = lipgloss.NewStyle().
			Foreground(ColorSpinner)
)
