// gen-styles reads kukuvaia-theme.yaml and generates styles_gen.go with Lipgloss constants.
//
// Usage: go run ./internal/tools/gen-styles -theme path/to/theme.yaml -out styles_gen.go
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"

	"gopkg.in/yaml.v3"
)

type theme struct {
	Colors   map[string]string `yaml:"colors"`
	Table    map[string]any    `yaml:"table"`
	Panel    map[string]any    `yaml:"panel"`
	Code     map[string]string `yaml:"code"`
	Progress map[string]string `yaml:"progress"`
	Status   map[string]string `yaml:"status"`
	Spacing  map[string]int    `yaml:"spacing"`
}

func main() {
	themePath := flag.String("theme", "kukuvaia-theme.yaml", "path to theme YAML")
	outPath := flag.String("out", "styles_gen.go", "output Go file")
	flag.Parse()

	data, err := os.ReadFile(*themePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read theme: %v\n", err)
		os.Exit(1)
	}

	var t theme
	if err := yaml.Unmarshal(data, &t); err != nil {
		fmt.Fprintf(os.Stderr, "parse theme: %v\n", err)
		os.Exit(1)
	}

	src := generate(t)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\nsource:\n%s\n", err, src)
		os.Exit(1)
	}

	if err := os.WriteFile(*outPath, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated %s from %s\n", *outPath, *themePath)
}

func generate(t theme) string {
	// Extract padding as ints
	padV, padH := 0, 1
	if p, ok := t.Panel["padding"]; ok {
		if arr, ok := p.([]any); ok && len(arr) >= 2 {
			if v, ok := arr[0].(int); ok {
				padV = v
			}
			if v, ok := arr[1].(int); ok {
				padH = v
			}
		}
	}

	return fmt.Sprintf(`// Code generated by gen-styles from kukuvaia-theme.yaml. DO NOT EDIT.

package tui

import "github.com/charmbracelet/lipgloss"

// --- Color constants ---

var (
	ColorPrimary    = lipgloss.Color(%q)
	ColorSuccess    = lipgloss.Color(%q)
	ColorError      = lipgloss.Color(%q)
	ColorWarning    = lipgloss.Color(%q)
	ColorMuted      = lipgloss.Color(%q)
	ColorText       = lipgloss.Color(%q)
	ColorBackground = lipgloss.Color(%q)
	ColorSurface    = lipgloss.Color(%q)
	ColorBorder     = lipgloss.Color(%q)
)

// --- Status colors ---

var (
	ColorPass    = lipgloss.Color(%q)
	ColorFail    = lipgloss.Color(%q)
	ColorPending = lipgloss.Color(%q)
	ColorSkip    = lipgloss.Color(%q)
)

// --- Progress colors ---

var (
	ColorProgressFilled = lipgloss.Color(%q)
	ColorProgressEmpty  = lipgloss.Color(%q)
	ColorSpinner        = lipgloss.Color(%q)
)

// --- Code block colors ---

var (
	ColorCodeBg     = lipgloss.Color(%q)
	ColorCodeBorder = lipgloss.Color(%q)
	ColorCodeText   = lipgloss.Color(%q)
)

// --- Table colors ---

var (
	ColorTableHeaderBg = lipgloss.Color(%q)
	ColorTableHeaderFg = lipgloss.Color(%q)
	ColorTableRowAlt   = lipgloss.Color(%q)
	ColorTableBorder   = lipgloss.Color(%q)
)

// --- Spacing ---

const (
	SpacingBlockGap   = %d
	SpacingSectionGap = %d
)

// --- Composed styles ---

var (
	TitleStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(ColorPrimary)

	ErrorStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(ColorError)

	WarningStyle = lipgloss.NewStyle().
			Foreground(ColorWarning)

	MutedStyle = lipgloss.NewStyle().
			Foreground(ColorMuted)

	PanelStyle = lipgloss.NewStyle().
			Border(lipgloss.RoundedBorder()).
			BorderForeground(ColorBorder).
			Padding(%d, %d)

	PanelTitleStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color(%q)).
			Background(ColorBorder).
			Padding(0, 1)

	CodeBlockStyle = lipgloss.NewStyle().
			Background(ColorCodeBg).
			Border(lipgloss.RoundedBorder()).
			BorderForeground(ColorCodeBorder).
			Padding(0, 1)

	TableHeaderStyle = lipgloss.NewStyle().
			Bold(true).
			Foreground(ColorTableHeaderFg).
			Background(ColorTableHeaderBg).
			Padding(0, 1)

	UserMessageStyle = lipgloss.NewStyle().
			Foreground(ColorPrimary).
			Bold(true)

	SpinnerStyle = lipgloss.NewStyle().
			Foreground(ColorSpinner)
)
`,
		// Colors
		t.Colors["primary"], t.Colors["success"], t.Colors["error"], t.Colors["warning"],
		t.Colors["muted"], t.Colors["text"], t.Colors["background"], t.Colors["surface"],
		t.Colors["border"],
		// Status
		t.Status["pass"], t.Status["fail"], t.Status["pending"], t.Status["skip"],
		// Progress
		t.Progress["filled_color"], t.Progress["empty_color"], t.Progress["spinner_color"],
		// Code
		t.Code["background"], t.Code["border_color"], t.Code["text"],
		// Table
		str(t.Table["header_bg"]), str(t.Table["header_fg"]),
		str(t.Table["row_alt_bg"]), str(t.Table["border_color"]),
		// Spacing
		t.Spacing["block_gap"], t.Spacing["section_gap"],
		// Panel padding
		padV, padH,
		// Panel title color
		str(t.Panel["title_color"]),
	)
}

func str(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}
